### ISSUE TITLE
Couldn't include the library to Ardunio IDE 

### ISSUE THREAD

**Issue by BehicKlncky** [wachidsusilo/ArrayList#2]
I tried to include the library via including the zip. But the IDE gave me an error. Also there is no such library in library manager. ArrayList.h also includes itself. How can I include this?

**Comment by wachidsusilo** [comment]
Can you please show me the error?

**Comment by wachidsusilo** [comment]
You can also put `ArrayList.h` file into `src` directory inside your project folder. The file structure should look like this:
```
Project
  ├─ src
  │   └─ ArrayList.h
  └─ Project.ino
```
This is how to include the lib in your sketch:
```cpp
#include "src/ArrayList.h"

void setup() {
    // TODO
}

void loop() {
    // TODO
}
```

**Comment by BehicKlncky** [comment]
Okay I got it my bad. Have a great day!
